//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazeron.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlazeronLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlazeronLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazeron.Localization.BlazeronLocale", typeof(BlazeronLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string AlertLabel {
            get {
                return ResourceManager.GetString("AlertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple alert (Gradient).
        /// </summary>
        public static string AlertSimpleGradientLabel {
            get {
                return ResourceManager.GetString("AlertSimpleGradientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple alert.
        /// </summary>
        public static string AlertSimpleLabel {
            get {
                return ResourceManager.GetString("AlertSimpleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background colors.
        /// </summary>
        public static string BackgroundColorsLabel {
            get {
                return ResourceManager.GetString("BackgroundColorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string BadgeLabel {
            get {
                return ResourceManager.GetString("BadgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pill badges.
        /// </summary>
        public static string BadgePillLabel {
            get {
                return ResourceManager.GetString("BadgePillLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple badge.
        /// </summary>
        public static string BadgeSimpleLabel {
            get {
                return ResourceManager.GetString("BadgeSimpleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        public static string ButtonsLabel {
            get {
                return ResourceManager.GetString("ButtonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string CardLabel {
            get {
                return ResourceManager.GetString("CardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header and Footer.
        /// </summary>
        public static string CardWithHeaderAndFooter {
            get {
                return ResourceManager.GetString("CardWithHeaderAndFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default buttons.
        /// </summary>
        public static string DefaultButtonLabel {
            get {
                return ResourceManager.GetString("DefaultButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple card.
        /// </summary>
        public static string DefaultCardLabel {
            get {
                return ResourceManager.GetString("DefaultCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Dismissing Alert.
        /// </summary>
        public static string DismissingAlertHideLabel {
            get {
                return ResourceManager.GetString("DismissingAlertHideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dismissing Alert.
        /// </summary>
        public static string DismissingAlertShowLabel {
            get {
                return ResourceManager.GetString("DismissingAlertShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissing - Effects.
        /// </summary>
        public static string DismissingEffectsLabel {
            get {
                return ResourceManager.GetString("DismissingEffectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissing.
        /// </summary>
        public static string DismissingLabel {
            get {
                return ResourceManager.GetString("DismissingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra large button.
        /// </summary>
        public static string ExtraLargeButtonLabel {
            get {
                return ResourceManager.GetString("ExtraLargeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra small button.
        /// </summary>
        public static string ExtraSmallButtonLabel {
            get {
                return ResourceManager.GetString("ExtraSmallButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient buttons.
        /// </summary>
        public static string GradientButtonLabel {
            get {
                return ResourceManager.GetString("GradientButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon buttons (Left).
        /// </summary>
        public static string IconButtonLeftLabel {
            get {
                return ResourceManager.GetString("IconButtonLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon buttons (Right).
        /// </summary>
        public static string IconButtonRightLabel {
            get {
                return ResourceManager.GetString("IconButtonRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string IconsLabel {
            get {
                return ResourceManager.GetString("IconsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string InboxLabel {
            get {
                return ResourceManager.GetString("InboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large button.
        /// </summary>
        public static string LargeButtonLabel {
            get {
                return ResourceManager.GetString("LargeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium button.
        /// </summary>
        public static string MediumButtonLabel {
            get {
                return ResourceManager.GetString("MediumButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New alerts.
        /// </summary>
        public static string NewAlertsLabel {
            get {
                return ResourceManager.GetString("NewAlertsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsLabel {
            get {
                return ResourceManager.GetString("NotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline disabled.
        /// </summary>
        public static string OutlineButtonDisabledLabel {
            get {
                return ResourceManager.GetString("OutlineButtonDisabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline buttons.
        /// </summary>
        public static string OutlineButtonLabel {
            get {
                return ResourceManager.GetString("OutlineButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positioned.
        /// </summary>
        public static string PositionedLabel {
            get {
                return ResourceManager.GetString("PositionedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressLabel {
            get {
                return ResourceManager.GetString("ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string ReferenceLabel {
            get {
                return ResourceManager.GetString("ReferenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string SizesLabel {
            get {
                return ResourceManager.GetString("SizesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small button.
        /// </summary>
        public static string SmallButtonLabel {
            get {
                return ResourceManager.GetString("SmallButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid disabled.
        /// </summary>
        public static string SolidButtonDisabledLabel {
            get {
                return ResourceManager.GetString("SolidButtonDisabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type and press enter....
        /// </summary>
        public static string TagsInputDefaultPlaceholderValue {
            get {
                return ResourceManager.GetString("TagsInputDefaultPlaceholderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags Input.
        /// </summary>
        public static string TagsInputLabel {
            get {
                return ResourceManager.GetString("TagsInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string TemplateLabel {
            get {
                return ResourceManager.GetString("TemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unread messages.
        /// </summary>
        public static string UnreadMessagesLabel {
            get {
                return ResourceManager.GetString("UnreadMessagesLabel", resourceCulture);
            }
        }
    }
}
